### ISSUE TITLE
Documentación del apartado 4 (Solution Strategy)

### ISSUE THREAD

**Issue by moiSS00** [Arquisoft/radarin_es4b#11]
Realización del apartado 4 (Solution Strategy).

- Moisés Sanjurjo Sánchez

**Comment by moiSS00** [comment]
Primer commit para la realización de esta tarea: 31bc5877b705419778137bbd6175d13a3f36bacc

**Comment by moiSS00** [comment]
Tarea finalizada en el commit 986e5fe54b49de86890a6db77fa2cbe349d37ca5

**Comment by UO266640** [comment]
23db7bddf67167b05a5af1586d11102a02dfa2df

36e473573e78299f1868d5c2d7bbda55b4986131
