### ISSUE TITLE
Error en los diagramas 

### ISSUE THREAD

**Issue by UO266640** [Arquisoft/radarin_es4b#21]
Hay un error en los diagramas de la documentación, en los puntos 3 y 5, provocando que estos no se generen correctamente.

**Comment by UO266640** [comment]
El error estaba en la forma de implementar los UML en ADOC, lo hemos resuelto usando solo la parte del UML, que funciona sin errores, en un [editor online de plantuml](https://www.planttext.com/), exportando el resultado en png, y colocandolas en la documentación.

**Comment by UO270571** [comment]
Resuelto en 62a9ed3936a29fa1e45561f022272556668631d1 y 52a409c306926c54f0abcc73ecf9e7029253e785. Había que añadir el paquete graphviz a la imagen Docker de la aplicación web para que se viesen los diagramas.
