### ISSUE TITLE
Prototipo mapa

### ISSUE THREAD

**Issue by UO266640** [Arquisoft/radarin_es4b#25]

**Comment by UO266640** [comment]
b641640d07abc0d869d76b06a7de32b9dd94604b

**Comment by UO270571** [comment]
Integrado con el formulario de url en 8070e509229439de1b67ededd605d48ff79c2081

**Comment by UO266640** [comment]
381eac47bdd7c64351b9d6db34764275951b8256
4ba5465930c899b9fc54ae40c58cbb745f134674
