### ISSUE TITLE
Investigación React Native

### ISSUE THREAD

**Issue by UO265181** [Arquisoft/radarin_es4b#28]

**Comment by UO270571** [comment]
Creado el esqueleto de la app móvil en c8e2839665d1e85cc852f435db3215a74a2de1d4

**Comment by UO266640** [comment]
bafa525c8f112b4cf655a80d5ed3b71944ccc03d
3db436746977283fb31d6d5dac917fb12397316b
b1b9f0b3250f31f161e0c796f1290953108b8f2c
