### ISSUE TITLE
Error al realizar un logOut

### ISSUE THREAD

**Issue by UO265181** [Arquisoft/radarin_es4b#29]
Realizo un logOut de solid usando solid-auth-client de la siguiente manera.
solidauth.logout().then(() => alert('Has desvinculado tu Pod'));

El logOut se efectúa pero la consola imprime el siguiente error:
GET http://localhost:3000/.well-known/solid/logout 404 (Not Found)

![image](https://user-images.githubusercontent.com/71436480/111090556-6edf8980-8530-11eb-93a9-31e978eea138.png)

**Comment by UO265181** [comment]
La captura anterior es Edge. Con Chrome ocurre lo mismo. En Firefox no se muestra el error pero estoy con una versión antigua (V 65.0.1  64bits)

**Comment by moiSS00** [comment]
Tras varias pruebas, se ha localizado el problema. Se estaba utilizando una URL de popup para loguearse  errónea / desactualizada. Se solucionó el error cambiando la URL de popup que teníamos por una más actual (https://solid.github.io/solid-auth-client/dist/popup.html).
