### ISSUE TITLE
Creación de pruebas unitarias. 

### ISSUE THREAD

**Issue by moiSS00** [Arquisoft/radarin_es4b#40]

**Comment by UO270571** [comment]
Pruebas iniciales de la api rest en 2c203c4b8ad6d7fbf7a53815f817b53589532a46.
Test actualizados en 64555d544f9d69b0bf8f56ed79e25bf9cf0d94b2.
Test añadidos a la cobertura de código en 5a8faa5691d5e36066dc6e922022e9977b04f6f6.

**Comment by UO270571** [comment]
Pruebas unitarias de la app móvil en [esta issue](https://github.com/Arquisoft/radarin_es4b/issues/47)

**Comment by UO270571** [comment]
Pruebas unitarias de la aplicación web en [esta issue](https://github.com/Arquisoft/radarin_es4b/issues/66)

**Comment by UO270571** [comment]
Más pruebas para la api rest en e5cb6d87a152f68236516674d0b1600b27c27450
