### ISSUE TITLE
Actualizar documentación

### ISSUE THREAD

**Issue by UO270571** [Arquisoft/radarin_es4b#43]
Actualizar documentación de cara a la presentación de la primera release

**Comment by UO270571** [comment]
Actualización con aspectos de la app móvil 1da4ad525b41f354e77dac696d27d807b43d5a78

**Comment by UO266640** [comment]
bd4619d3478ca83f6498de91075b83464abaf5fd
36e473573e78299f1868d5c2d7bbda55b4986131
23db7bddf67167b05a5af1586d11102a02dfa2df
8aa47db1cfca79442f80d9977d4bab5987cdb318

**Comment by UO270571** [comment]
2a87cd8d66cf88b5dd18a30d2593f9b59b72d4d5

**Comment by UO270571** [comment]
Añadidas tecnologías usadas en React Native b9d780da6d4f86c0c29880c29d61ad9426a39358
