### ISSUE TITLE
Añadir amigo cuando el usuario no tiene amigos

### ISSUE THREAD

**Issue by UO265181** [Arquisoft/radarin_es4b#44]
En un pod se accede a los amigos usando la lista knows de un pod.
Esta lista la crea el servidor de pod una vez se añade un amigo por lo que es necesaria crearla si aún no se tiene ningún amigo.
He intentado crearla usando @solid/query-ldflex y:
-> knows.add(...)
-> knows.set(...)
pero no ha dado resultado.

**Comment by uo269450** [comment]
Hola, quizás esto te sirva de ayuda: https://github.com/taisukef/solid-addfriend/blob/master/scripts/main.js

**Comment by UO265181** [comment]
El error se encontraba en los permisos del Pod. Un usuario sin amigos puede añadir amigos sin problema si da los permisos nuestra página.
