### ISSUE TITLE
Pruebas unitarias app móvil

### ISSUE THREAD

**Issue by UO266640** [Arquisoft/radarin_es4b#47]

**Comment by UO266640** [comment]
0b2d84e058a4b06d71fe27522e6f1171b7e28659

**Comment by UO270571** [comment]
Más pruebas en  89c96b9cb9d1360e92c1eeff57966d9f2c30322f y en c76bcc05844ba6fbdd8d4253087662941c5ef949

**Comment by UO270571** [comment]
Más pruebas añadidas en 7ca3130db4f5603f1641429835219acb97a951c4
