### ISSUE TITLE
Servicio de administración en la aplicación web

### ISSUE THREAD

**Issue by UO265181** [Arquisoft/radarin_es4b#52]
Gestión de usuarios del sistema.

**Comment by UO265181** [comment]
Funcionalidad añadida.
80da4f48afd7ab28e510e98011253abbd48f3a20
3aa7538c0490f71d7395833c9ef4d5b70d8bc063
Los usuarios baneados no se contemplan aún.

**Comment by UO270571** [comment]
Gestión de baneados en la app móvil añadido en 7ca3130db4f5603f1641429835219acb97a951c4

**Comment by UO265181** [comment]
7c1dfe006a685d7c985437fc08bc301457a56224
40ca33f71a533f20460c23c5382588d1a4e7c5ef
