### ISSUE TITLE
Internacionalización de la aplicación web

### ISSUE THREAD

**Issue by moiSS00** [Arquisoft/radarin_es4b#53]
La aplicación móvil ya está internacionalizada. Falta por internacionalizar la aplicación web.

**Comment by moiSS00** [comment]
Tras varios commits, la base para la internacionalización en la aplicación web finaliza en 10d6944bc95a7841569636086ad6b2d524c005b4

Posteriormente se procedió a internacionalizar en inglés / español los textos de la aplicación web: 
* Página de login y menú de navegación: fb42b75b7c8c25b6ce5bd9f0e88b309408ad99e9
* Página personal del usuario y mapa: 2c39cf539dd2a4ffc5404df5c5a4cd454d1ed3aa
* Lista de amigos: 1726c41b11206d0f06e5956a81a2958b6a900f22

**Comment by UO265181** [comment]
Añadida internacionalización de la administración web
80da4f48afd7ab28e510e98011253abbd48f3a20

**Comment by UO265181** [comment]
Añadida internacionalización de la página de ban
40ca33f71a533f20460c23c5382588d1a4e7c5ef
