### ISSUE TITLE
Anexo pruebas en la documentación

### ISSUE THREAD

**Issue by moiSS00** [Arquisoft/radarin_es4b#67]
Redacción del anexo con la información de todas las pruebas realizadas.

**Comment by UO270571** [comment]
Más documentación sobre pruebas en eed4462cabece5069a4f19759ba14d7a73616457

**Comment by moiSS00** [comment]
Más documentación sobre pruebas unitarias de la app web en 41d1d2a1639870f7cc0c359c199fe7a2cff58bac
