### ISSUE TITLE
Error radio amigos cercanos en la app web

### ISSUE THREAD

**Issue by moiSS00** [Arquisoft/radarin_es4b#77]
En la sección del mapa de la aplicación web, al hacer zoom en un usuario, se pierde el radio / centro de búsqueda por error y se obliga al usuario a volver a usar el slider para visualizar correctamente a los amigos cercanos.

**Comment by UO270571** [comment]
Solucionado en 32721cbe9f8a32f11092c51f5ea6031dac3830b6
